---
theme: "coar_notify"
languageCode: "en-gb"
uglyURLs: false
title: "COAR Notify"
enableRobotsTXT: true
enableGitInfo: false
disablePathToLower: true
services:
  rss:
    limit: 20
outputs:
  home:
    - html
    - json
  section:
    - html
    - rss
  taxonomy:
    - html
  term:
    - html
  page:
    - html
    - json
permalinks:
  page:
    posts: "/:year/:filename/"
taxonomies:
  tag: "tags"
  pattern-category: "pattern-categories"
  use-case: "use-cases"
  implementation-type: "implementation-types"
caches:
  getjson:
    dir: :cacheDir/:project
    maxAge: 5s
  getresource:
    dir: :cacheDir/:project
    maxAge: 5s
  getcsv:
    dir: :cacheDir/:project
    maxAge: 5s
params:
  siteHeaderMessage:
    enable: false
    text: |
      This is a development version of the COAR Notify documentation website.
      The content here is **subject to change without warning**.
      The current, supported version is at [https://notify.coar-repositories.org](https://notify.coar-repositories.org).
  currentSpecificationVersion: "1.0.0"
  eventNotificationsPatternsBaseURL: "https://www.eventnotifications.net/"
  enableAnalytics: false  # this param may be overridden in production/development envs
  googleSiteVerification:
  fundingAcknowledgementText: "The development of this work is funded in part by a generous grant from [Arcadia](https://www.arcadiafund.org.uk)."
  gitHubRepoForSources: "https://github.com/coar-notify/coar-notify.net"
  feedbackFormURL: "https://github.com/coar-notify/coar-notify.net/issues/new?assignees=paulwalk&labels=feedback&template=feedback.md&title=PLACEHOLDER"
  mermaid:
#    left_node_colour: "#ddedea"
#    right_node_colour: "#daeaf6"
#    notify_node_colour: "#e8dff5"
    left_node_colour: "#f7d878" #this colour palette from https://www.schemecolor.com/tender-touch.php
    right_node_colour: "#aec9d3"
    notify_node_colour: "#e6c5d4"
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    extensions:
      definitionList: true
      footnote: true
      linkify: false
      strikethrough: false
      table: true
      taskList: true
      typographer: false
      extras:
        delete:
          enable: true
        insert:
          enable: true
        mark:
          enable: true
        subscript:
          enable: true
        superscript:
          enable: true
    parser:
      attribute:
        block: true
        title: true
      autoHeadingID: true
    #      wrapStandAloneImageWithinParagraph: false
    renderer:
      hardWraps: false
      unsafe: true
      xhtml: false
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    lineAnchors: ""
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: false
    style: pygments
    tabWidth: 4
---